### PR TITLE
Fixing a justification error in the XSS example.

### PR DESCRIPTION
**Pull request by jlconlin**

### CODE REVIEW

**Comment by paulromano** [comment]
@jlconlin did you want to update the PDF in the repo too?

**Comment by whaeck** [comment]
@paulromano I think the pdf was updated (although I did not look at the pdf).

**Comment by paulromano** [comment]
Oops you're right. Somehow I missed that!

**Review by whaeck — APPROVED** [review]
There's only cosmetic changes, so fine by me.

**Comment by jlconlin** [comment]
Thanks @whaeck and @paulromano. While it may look like cosmetic changes, it does cause some confusion for those who are trying to work with the format.

**Pull request merged**
