### PR TITLE
Clarifying unresolved resonance stuff.

### PR DESCRIPTION
**Pull request by jlconlin**

### CODE REVIEW

**Comment by jlconlin** [comment]
@paulromano I'm trying to make the changes you suggested. However, I'm struggling to compile the document. Even with a fresh clone I can't get the document to compile. I'm not sure what went wrong. Are you able to compile it?

**Comment by jlconlin** [comment]
@paulromano Never mind, I think I've figured it out.

**Comment by jlconlin** [comment]
I've updated this according to @paulromano's suggestion. I've also done a little bit of cleanup to make things a little more consistent.

**Comment by paulromano** [comment]
Table 60 seems to run into the footer and the page number appears within the table. Does the same thing appear for you @jlconlin?

**Comment by jlconlin** [comment]
Yeah, @paulromano, it does. This isn't the only time this happens. I simply haven't had the cycles to look into why this happens. Presumably LaTeX is supposed to take care of that for me. I'm guessing my use of `longtable`s may be interfering.

**Comment by paulromano** [comment]
Hmm, I don't know offhand how to fix it. As long as you're satisfied with how it looks at present, I'm also ok with the changes provided. Let's just create an issue for the longtables issue so it's not forgotten

**Comment by jlconlin** [comment]
I've been meaning to look into this, but haven't had the time to do so.

**Pull request merged**
